---
# Source: mq-quarkus-app/templates/configmap-ccdt.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: mq-quarkus-app-ccdt
data:
  ccdt.json: |
    {
      "channel": [
        {
          "name": "MIQMCHL",
          "clientConnection": {
            "connection": [
              {
                "host": "qm1-dev-ibm-mq.dev.svc.cluster.local",
                "port": 443
              }
            ],
            "queueManager": "QM1"
          },
          "type": "clientConnection"
        }
      ]
    }
